
name: Terraform Plan on Pull Master

on:
  pull_request:
    branches:
      - master

permissions:
  id-token: write   # Required for Federated Credentials
  contents: read

jobs:
  terraform:
    name: Terraform Plan
    runs-on: ubuntu-latest

    env:
      ARM_USE_OIDC: true   # Enables Federated Credentials for Azure
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      TF_VAR_resource_group: "myResourceGroup"
      TF_VAR_storage_account: "mystorageaccount"
      TF_VAR_container_name: "tfstate"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Azure Login using Federated Credentials
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Terraform Init
        run: |
          terraform init -backend-config="resource_group_name=${TF_VAR_resource_group}" \
                         -backend-config="storage_account_name=${TF_VAR_storage_account}" \
                         -backend-config="container_name=${TF_VAR_container_name}" \
                         -backend-config="key=terraform.tfstate"

      - name: Terraform Plan
        run: terraform plan -var-file="prod/terraform.tfvars"
